### ISSUE TITLE
https://octocard.in down?

### ISSUE THREAD

**Issue by dschuermann** [zmmbreeze/octocard#26]
Looks like https://octocard.in does not work anymore. Any updates on this?

**Comment by zmmbreeze** [comment]
Something broke on the VPS hosting service. I'm working on it. It may take a few days.

**Comment by augnustin** [comment]
+1 still down, isn't it?

**Comment by zhengxiaoyao0716** [comment]
+1, 弃坑了？？？

**Comment by zmmbreeze** [comment]
I'm afraid this project has been shutdown. Thank you for your support.

**Comment by augnustin** [comment]
If this can help, as far as I'm concerned I moved to https://github.com/surbhioberoi/github-widget

Among other possibilities, I chose this one because **there are no external dependencies**, which could break the widget like it happened here.

I made up a self hosted version with the widget JS https://github.com/surbhioberoi/github-widget/blob/master/src/widget.js and a 100% customized CSS from the SASS original file https://github.com/surbhioberoi/github-widget/blob/master/src/widget.scss.

The result is in the footer of my portfolio : http://augustin-riedinger.fr

**Comment by zhengxiaoyao0716** [comment]
@aug-riedinger  Nice, it's really what i need, thanks a lot.

**Comment by zmmbreeze** [comment]
@aug-riedinger 👍
